upgraded 130 some packages. still working.

diff --git a/partial_test2/usr/bin/zforce b/partial_test2/usr/bin/zforce
--- a/partial_test2/usr/bin/zforce
+++ b/partial_test2/usr/bin/zforce
@@ -6,7 +6,7 @@
 # 12345678901234 is renamed to 12345678901.gz
 
 
-# Copyright (C) 2002, 2007 Free Software Foundation
+# Copyright (C) 2002, 2007, 2010 Free Software Foundation
 # Copyright (C) 1993 Jean-loup Gailly
 
 # This program is free software; you can redistribute it and/or modify
@@ -29,8 +29,8 @@ case $1 in
 esac
 PATH=$bindir:$PATH; export PATH
 
-version="zforce (gzip) 1.4
-Copyright (C) 2007, 2009-2010 Free Software Foundation, Inc.
+version="zforce (gzip) 1.6
+Copyright (C) 2010-2013 Free Software Foundation, Inc.
 This is free software.  You may redistribute copies of it under the terms of
 the GNU General Public License <http://www.gnu.org/licenses/gpl.html>.
 There is NO WARRANTY, to the extent permitted by law.
@@ -44,7 +44,7 @@ not compress them twice.
 Report bugs to <bug-gzip@gnu.org>."
 
 if test $# = 0; then
-  echo "$usage"
+  echo >&2 "$0: invalid number of operands; try \`$0 --help' for help"
   exit 1
 fi
 
